----------------------------------------------------------------------
-- WS_DATASTE_INFO - Musterkonfiguration für alle Webdienste.
----------------------------------------------------------------------
-- PUBLIC
-- Verwendung auf eigene Gefahr!
-- Script wird nicht supportet, es besteht kein Anspruch auf Vollständigkeit oder Korrektheit.
----------------------------------------------------------------------
-- [01.04.2025] V 1.2 / GEOBOX AG (USO) - Script verbessert.
----------------------------------------------------------------------

-- *******************************************************************
-- CHECK-ID: 080201
-- Einstellung eintragen
-- *******************************************************************
INSERT INTO WS_DATASET_INFO (DATE_LAST_UPDATE,DATASET_VERSION,ENDPOINT_URI,ACTIVE,DATASET_NAME,BOUNDING_BOX,ID,IMPORT_TYPE,NARRATIVE,DATASET_KEY) VALUES (TO_DATE('01.01.2026 00:00:00','DD.MM.YYYY HH24:MI:SS'),'2024.07.13','https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry={bbox}&geometryType=esriGeometryEnvelope&sr=2056&layers=all%3Ach.swisstopo.fixpunkte-lfp1&tolerance=0&geometryFormat=geojson&limit=200',1,'Lagefixpunkte LFP1 (Landesvermessung)','2720350,1255450,2722700,1257250',1,'fixpunkte_lfp1.release_20260204','Bundesamt für Landestopografie swisstopo - Fixpunkte Landesvermessung (https://opendata.swiss/de/dataset/lagefixpunkte-lfp1-landesvermessung)','FixpunkteLV_LFP1');
INSERT INTO WS_DATASET_INFO (DATE_LAST_UPDATE,DATASET_VERSION,ENDPOINT_URI,ACTIVE,DATASET_NAME,BOUNDING_BOX,ID,IMPORT_TYPE,NARRATIVE,DATASET_KEY) VALUES (TO_DATE('01.01.2026 00:00:00','DD.MM.YYYY HH24:MI:SS'),'2024.07.13','https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry={bbox}&geometryType=esriGeometryEnvelope&sr=2056&layers=all%3Ach.swisstopo.fixpunkte-hfp1&tolerance=0&geometryFormat=geojson&limit=200',1,'Höhenfixpunkte HFP1 (Landesvermessung)','2720350,1255450,2722700,1257250',2,'fixpunkte_hfp1.release_20260204','Bundesamt für Landestopografie swisstopo - Fixpunkte Landesvermessung (https://opendata.swiss/de/dataset/hohenfixpunkte-hfp1-landesvermessung)','FixpunkteLV_HFP1');
INSERT INTO WS_DATASET_INFO (DATE_LAST_UPDATE,DATASET_VERSION,ENDPOINT_URI,ACTIVE,DATASET_NAME,BOUNDING_BOX,ID,IMPORT_TYPE,NARRATIVE,DATASET_KEY) VALUES (TO_DATE('01.01.2026 00:00:00','DD.MM.YYYY HH24:MI:SS'),'2024.07.13','https://www.geodienste.ch/db/fixpunkte_v1_1_0/deu/ogcapi/collections/fixpunkte/items?f=json&bbox={bbox}&bbox-crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F2056&offset=0&limit=10000',1,'Fixpunkte (Kategorie 2)','2720350,1255450,2722700,1257250',3,'fixpunkte_fp2.v1_1_0','geodienste.ch (KGK) - Fixpunkte (Kategorie 2) (https://www.geodienste.ch/services/fixpunkte)','FixpunkteLV_FP2');
INSERT INTO WS_DATASET_INFO (DATE_LAST_UPDATE,DATASET_VERSION,ENDPOINT_URI,ACTIVE,DATASET_NAME,BOUNDING_BOX,ID,IMPORT_TYPE,NARRATIVE,DATASET_KEY) VALUES (TO_DATE('01.01.2026 00:00:00','DD.MM.YYYY HH24:MI:SS'),'2024.07.13','https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry={bbox}&geometryType=esriGeometryEnvelope&sr=2056&layers=all%3Ach.swisstopo.hoheitsgrenze-landesvermessung&tolerance=0&geometryFormat=geojson&limit=200',1,'Hoheitsgrenze (Landesvermessung)','2720350,1255450,2722700,1257250',4,'hoheitsgrenze_lv.release_20260204','Bundesamt für Landestopografie swisstopo - Hoheitsgrenze Landesvermessung - Landesgrenze (https://opendata.swiss/de/dataset/hoheitsgrenzelv)','HoheitsgrenzenLV_Landesgrenze');
INSERT INTO WS_DATASET_INFO (DATE_LAST_UPDATE,DATASET_VERSION,ENDPOINT_URI,ACTIVE,DATASET_NAME,BOUNDING_BOX,ID,IMPORT_TYPE,NARRATIVE,DATASET_KEY) VALUES (TO_DATE('01.01.2026 00:00:00','DD.MM.YYYY HH24:MI:SS'),'2024.07.13','https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry={bbox}&geometryType=esriGeometryEnvelope&sr=2056&layers=all%3Ach.swisstopo-vd.ortschaftenverzeichnis_plz&tolerance=0&geometryFormat=geojson&limit=200',1,'Amtliches Ortschaftenverzeichnis mit PLZ','2720350,1255450,2722700,1257250',5,'ortschaftenverzeichnis_plz.release_20260204','Bundesamt für Landestopografie swisstopo - Amtliches Ortschaftenverzeichnis mit Postleitzahl und Perimeter (https://opendata.swiss/de/dataset/amtliches-ortschaftenverzeichnis-mit-postleitzahl-und-perimeter)','Ortschaftenverzeichnis_PLZ');
commit;